### ISSUE TITLE
Image on Menu page not loading

### ISSUE THREAD

**Issue by karlwithak** [Paulinakhew/web_trader#1]
Hi Paulina!

I tried out this app, and had an issue when rendering the menu page:
<img width="675" alt="screen shot 2018-09-26 at 9 06 20 pm" src="https://user-images.githubusercontent.com/3248771/46117628-3cab0780-c1d0-11e8-9b63-e5242c8c8a0e.png">

I got a 403 error attempting to fetch this image. It looks like it is hosted on a third party storage platform, and doesn't have public read permissions set.

**Comment by Paulinakhew** [comment]
Hey @karlwithak ,
 Sorry I just saw this yesterday! I fixed the issue with all of the photos.
![screen shot 2019-02-02 at 7 53 01 pm](https://user-images.githubusercontent.com/40904028/52171088-719e0c80-2724-11e9-9338-cc9200631793.png)
This is a preview of what it looks like now. Feel free to give me some more tips and insight.
Thanks!
